### ISSUE TITLE
Reauthenticate Integration on each new startup

### ISSUE THREAD

**Issue by Bison010** [dougiteixeira/proxmoxve#338]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Every time I start up the server it asks for authentication.
<img width="166" alt="image" src="https://github.com/user-attachments/assets/f4fa7552-f016-4948-a1a7-10f04a6c11fc">
<img width="315" alt="image" src="https://github.com/user-attachments/assets/00bfe8eb-1551-4249-97d2-b920a9a303df">
Can this authentication persist across restarts, or can I automate the reauthentication?

### In which version of Home Assistant Core do you have the problem?

core-2024.7.4

### What version of Proxmox VE Custom Integration has the issue?

version 3.4.4

### What version of Proxmox VE do you have the problem?

proxmox 8.2.4 (running kernel: 6.8.8-2-pve)

**Comment by lukas1906** [comment]
I have the same issue. Are there any work arounds?

**Comment by KentBrockman** [comment]
I also am having this issue

**Comment by ankostis** [comment]
Would authenticating via API-token fix this?

**Comment by amasolov** [comment]
I've made a fork and changed the source code to accommodate API token authentication instead of basic auth. It's a dirty hack and you would need to create a token named 'homeassistant' in Proxmox. Use your token value as password in this integration. 

Integration to add: https://github.com/amasolov/proxmoxve

The change from the original integration: https://github.com/amasolov/proxmoxve/commit/81643080d9c0ef37f106afa76b1e3a27ee00679f

I'm not going to pretend that it's a good solution. It's a quick workaround I needed and it works.

**Comment by ankostis** [comment]
If it didn't force the username, would it be fgood for a pull-request?

**Comment by amasolov** [comment]
@ankostis I wanted to make a proper PR following a similar approach but it required changing many small bits here and there. Felt like  a big effort.

**Comment by Markus-D-M** [comment]
I created a pull request for this. It's my first homeassistant related pr so I hope I haven't missed anything.

**Comment by amasolov** [comment]
@dougiteixeira your review will be very much appreciated

**Comment by Bison010** [comment]
Thanks Guys, great work so far lets keep the momentum going.

**Comment by dougiteixeira** [comment]
I believe that the use of authentication token implemented in #343 solves this definitively.

Released in version 3.5.0
